# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceBeautificationGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FaceBeautificationGUI(object):
    def setupUi(self, FaceBeautificationGUI):
        FaceBeautificationGUI.setObjectName("FaceBeautificationGUI")
        FaceBeautificationGUI.resize(981, 630)
        self.centralwidget = QtWidgets.QWidget(FaceBeautificationGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.m_options = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_options.sizePolicy().hasHeightForWidth())
        self.m_options.setSizePolicy(sizePolicy)
        self.m_options.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_options.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.m_options.setWidgetResizable(True)
        self.m_options.setObjectName("m_options")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -30, 252, 580))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.m_gender_male = QtWidgets.QRadioButton(self.groupBox_4)
        self.m_gender_male.setChecked(True)
        self.m_gender_male.setObjectName("m_gender_male")
        self.horizontalLayout_4.addWidget(self.m_gender_male)
        self.m_gender_female = QtWidgets.QRadioButton(self.groupBox_4)
        self.m_gender_female.setObjectName("m_gender_female")
        self.horizontalLayout_4.addWidget(self.m_gender_female)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.m_knn_eyebrows = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_knn_eyebrows.setChecked(True)
        self.m_knn_eyebrows.setObjectName("m_knn_eyebrows")
        self.gridLayout.addWidget(self.m_knn_eyebrows, 0, 0, 1, 1)
        self.m_knn_eyes = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_knn_eyes.setChecked(True)
        self.m_knn_eyes.setObjectName("m_knn_eyes")
        self.gridLayout.addWidget(self.m_knn_eyes, 0, 1, 1, 1)
        self.m_knn_nose = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_knn_nose.setChecked(True)
        self.m_knn_nose.setObjectName("m_knn_nose")
        self.gridLayout.addWidget(self.m_knn_nose, 1, 0, 1, 1)
        self.m_knn_mouth = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_knn_mouth.setObjectName("m_knn_mouth")
        self.gridLayout.addWidget(self.m_knn_mouth, 1, 1, 1, 1)
        self.m_knn_outline = QtWidgets.QCheckBox(self.groupBox_2)
        self.m_knn_outline.setChecked(True)
        self.m_knn_outline.setObjectName("m_knn_outline")
        self.gridLayout.addWidget(self.m_knn_outline, 2, 0, 1, 1)
        self.m_knn_apply = QtWidgets.QPushButton(self.groupBox_2)
        self.m_knn_apply.setObjectName("m_knn_apply")
        self.gridLayout.addWidget(self.m_knn_apply, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.m_bigger_eyes_rate = QtWidgets.QSlider(self.groupBox_3)
        self.m_bigger_eyes_rate.setMinimum(-10)
        self.m_bigger_eyes_rate.setMaximum(10)
        self.m_bigger_eyes_rate.setOrientation(QtCore.Qt.Horizontal)
        self.m_bigger_eyes_rate.setObjectName("m_bigger_eyes_rate")
        self.verticalLayout.addWidget(self.m_bigger_eyes_rate)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.m_bigger_eyes_rate_label = QtWidgets.QLabel(self.groupBox_3)
        self.m_bigger_eyes_rate_label.setObjectName("m_bigger_eyes_rate_label")
        self.horizontalLayout.addWidget(self.m_bigger_eyes_rate_label)
        self.m_bigger_eyes_apply = QtWidgets.QPushButton(self.groupBox_3)
        self.m_bigger_eyes_apply.setObjectName("m_bigger_eyes_apply")
        self.horizontalLayout.addWidget(self.m_bigger_eyes_apply)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.m_thinner_outline_rate = QtWidgets.QSlider(self.groupBox_5)
        self.m_thinner_outline_rate.setMinimum(-10)
        self.m_thinner_outline_rate.setMaximum(10)
        self.m_thinner_outline_rate.setOrientation(QtCore.Qt.Horizontal)
        self.m_thinner_outline_rate.setObjectName("m_thinner_outline_rate")
        self.verticalLayout_2.addWidget(self.m_thinner_outline_rate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.m_thinner_outline_rate_label = QtWidgets.QLabel(self.groupBox_5)
        self.m_thinner_outline_rate_label.setObjectName("m_thinner_outline_rate_label")
        self.horizontalLayout_2.addWidget(self.m_thinner_outline_rate_label)
        self.m_thinner_outline_apply = QtWidgets.QPushButton(self.groupBox_5)
        self.m_thinner_outline_apply.setObjectName("m_thinner_outline_apply")
        self.horizontalLayout_2.addWidget(self.m_thinner_outline_apply)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.m_remove_beverage = QtWidgets.QPushButton(self.groupBox_8)
        self.m_remove_beverage.setObjectName("m_remove_beverage")
        self.verticalLayout_7.addWidget(self.m_remove_beverage)
        self.m_whitening = QtWidgets.QPushButton(self.groupBox_8)
        self.m_whitening.setObjectName("m_whitening")
        self.verticalLayout_7.addWidget(self.m_whitening)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        spacerItem = QtWidgets.QSpacerItem(20, 109, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.m_options.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.m_options)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.m_pic_scroll = QtWidgets.QScrollArea(self.groupBox_6)
        self.m_pic_scroll.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.m_pic_scroll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.m_pic_scroll.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m_pic_scroll.setLineWidth(1)
        self.m_pic_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_pic_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_pic_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.m_pic_scroll.setWidgetResizable(True)
        self.m_pic_scroll.setObjectName("m_pic_scroll")
        self.m_pic_scroll_body = QtWidgets.QWidget()
        self.m_pic_scroll_body.setGeometry(QtCore.QRect(0, 0, 320, 475))
        self.m_pic_scroll_body.setObjectName("m_pic_scroll_body")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.m_pic_scroll_body)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.m_pic_scroll_layout = QtWidgets.QVBoxLayout()
        self.m_pic_scroll_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.m_pic_scroll_layout.setSpacing(0)
        self.m_pic_scroll_layout.setObjectName("m_pic_scroll_layout")
        self.verticalLayout_8.addLayout(self.m_pic_scroll_layout)
        self.m_pic_scroll.setWidget(self.m_pic_scroll_body)
        self.verticalLayout_5.addWidget(self.m_pic_scroll)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.m_demo_scroll = QtWidgets.QScrollArea(self.groupBox_7)
        self.m_demo_scroll.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.m_demo_scroll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.m_demo_scroll.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m_demo_scroll.setLineWidth(1)
        self.m_demo_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_demo_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_demo_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.m_demo_scroll.setWidgetResizable(True)
        self.m_demo_scroll.setObjectName("m_demo_scroll")
        self.m_demo_scroll_body = QtWidgets.QWidget()
        self.m_demo_scroll_body.setGeometry(QtCore.QRect(0, 0, 319, 475))
        self.m_demo_scroll_body.setObjectName("m_demo_scroll_body")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.m_demo_scroll_body)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.m_demo_scroll_layout = QtWidgets.QVBoxLayout()
        self.m_demo_scroll_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.m_demo_scroll_layout.setSpacing(0)
        self.m_demo_scroll_layout.setObjectName("m_demo_scroll_layout")
        self.verticalLayout_9.addLayout(self.m_demo_scroll_layout)
        self.m_demo_scroll.setWidget(self.m_demo_scroll_body)
        self.verticalLayout_6.addWidget(self.m_demo_scroll)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        FaceBeautificationGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FaceBeautificationGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        FaceBeautificationGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FaceBeautificationGUI)
        self.statusbar.setObjectName("statusbar")
        FaceBeautificationGUI.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(FaceBeautificationGUI)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        FaceBeautificationGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.m_action_open = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_open.setObjectName("m_action_open")
        self.m_action_save = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_save.setObjectName("m_action_save")
        self.m_action_undo = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_undo.setObjectName("m_action_undo")
        self.m_action_redo = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_redo.setObjectName("m_action_redo")
        self.m_action_exit = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_exit.setObjectName("m_action_exit")
        self.m_action_about = QtWidgets.QAction(FaceBeautificationGUI)
        self.m_action_about.setObjectName("m_action_about")
        self.m_action_reset = QtWidgets.QAction(FaceBeautificationGUI)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/ui/res/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_action_reset.setIcon(icon)
        self.m_action_reset.setObjectName("m_action_reset")
        self.menufile.addAction(self.m_action_open)
        self.menufile.addAction(self.m_action_save)
        self.menufile.addSeparator()
        self.menufile.addAction(self.m_action_exit)
        self.menu_Edit.addAction(self.m_action_undo)
        self.menu_Edit.addAction(self.m_action_redo)
        self.menu_Help.addAction(self.m_action_about)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.m_action_open)
        self.toolBar.addAction(self.m_action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.m_action_undo)
        self.toolBar.addAction(self.m_action_redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.m_action_reset)

        self.retranslateUi(FaceBeautificationGUI)
        self.m_action_exit.triggered.connect(FaceBeautificationGUI.close)
        QtCore.QMetaObject.connectSlotsByName(FaceBeautificationGUI)

    def retranslateUi(self, FaceBeautificationGUI):
        _translate = QtCore.QCoreApplication.translate
        FaceBeautificationGUI.setWindowTitle(_translate("FaceBeautificationGUI", "FaceBeautification"))
        self.groupBox_4.setTitle(_translate("FaceBeautificationGUI", "Gender"))
        self.m_gender_male.setText(_translate("FaceBeautificationGUI", "male"))
        self.m_gender_female.setText(_translate("FaceBeautificationGUI", "female"))
        self.groupBox.setTitle(_translate("FaceBeautificationGUI", "Shape Adjust"))
        self.groupBox_2.setTitle(_translate("FaceBeautificationGUI", "KNN"))
        self.m_knn_eyebrows.setText(_translate("FaceBeautificationGUI", "Eyebrows"))
        self.m_knn_eyes.setText(_translate("FaceBeautificationGUI", "Eyes"))
        self.m_knn_nose.setText(_translate("FaceBeautificationGUI", "Nose"))
        self.m_knn_mouth.setText(_translate("FaceBeautificationGUI", "Mouth"))
        self.m_knn_outline.setText(_translate("FaceBeautificationGUI", "Outline"))
        self.m_knn_apply.setText(_translate("FaceBeautificationGUI", "Apply"))
        self.groupBox_3.setTitle(_translate("FaceBeautificationGUI", "Bigger Eyes"))
        self.label.setText(_translate("FaceBeautificationGUI", "Rate: "))
        self.m_bigger_eyes_rate_label.setText(_translate("FaceBeautificationGUI", "1.00"))
        self.m_bigger_eyes_apply.setText(_translate("FaceBeautificationGUI", "Apply"))
        self.groupBox_5.setTitle(_translate("FaceBeautificationGUI", "Thinner Outline"))
        self.label_3.setText(_translate("FaceBeautificationGUI", "Rate: "))
        self.m_thinner_outline_rate_label.setText(_translate("FaceBeautificationGUI", "1.00"))
        self.m_thinner_outline_apply.setText(_translate("FaceBeautificationGUI", "Apply"))
        self.groupBox_8.setTitle(_translate("FaceBeautificationGUI", "Skin Beautification"))
        self.m_remove_beverage.setText(_translate("FaceBeautificationGUI", "Remove Beverage"))
        self.m_whitening.setText(_translate("FaceBeautificationGUI", "Whitening"))
        self.groupBox_6.setTitle(_translate("FaceBeautificationGUI", "Original Image"))
        self.groupBox_7.setTitle(_translate("FaceBeautificationGUI", "Beautified Image"))
        self.menufile.setTitle(_translate("FaceBeautificationGUI", "&File"))
        self.menu_Edit.setTitle(_translate("FaceBeautificationGUI", "&Edit"))
        self.menu_Help.setTitle(_translate("FaceBeautificationGUI", "&Help"))
        self.toolBar.setWindowTitle(_translate("FaceBeautificationGUI", "toolBar"))
        self.m_action_open.setText(_translate("FaceBeautificationGUI", "&Open"))
        self.m_action_open.setToolTip(_translate("FaceBeautificationGUI", "<html><head/><body><p>Open a new image.</p></body></html>"))
        self.m_action_open.setShortcut(_translate("FaceBeautificationGUI", "Ctrl+O"))
        self.m_action_save.setText(_translate("FaceBeautificationGUI", "&Save"))
        self.m_action_save.setToolTip(_translate("FaceBeautificationGUI", "Save image."))
        self.m_action_save.setShortcut(_translate("FaceBeautificationGUI", "Ctrl+S"))
        self.m_action_undo.setText(_translate("FaceBeautificationGUI", "&Undo"))
        self.m_action_undo.setToolTip(_translate("FaceBeautificationGUI", "Undo."))
        self.m_action_undo.setShortcut(_translate("FaceBeautificationGUI", "Ctrl+Z"))
        self.m_action_redo.setText(_translate("FaceBeautificationGUI", "&Redo"))
        self.m_action_redo.setToolTip(_translate("FaceBeautificationGUI", "Redo."))
        self.m_action_redo.setShortcut(_translate("FaceBeautificationGUI", "Ctrl+Shift+Z"))
        self.m_action_exit.setText(_translate("FaceBeautificationGUI", "&Exit"))
        self.m_action_exit.setToolTip(_translate("FaceBeautificationGUI", "Exit."))
        self.m_action_about.setText(_translate("FaceBeautificationGUI", "&About"))
        self.m_action_about.setToolTip(_translate("FaceBeautificationGUI", "About."))
        self.m_action_reset.setText(_translate("FaceBeautificationGUI", "Reset"))
        self.m_action_reset.setToolTip(_translate("FaceBeautificationGUI", "Reset Image."))
        self.m_action_reset.setShortcut(_translate("FaceBeautificationGUI", "Ctrl+R"))

import FaceBeautificationGUI_rc
